FROM python:3.6-alpine

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY requirements-cli.txt requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add app
COPY currency_converter/currency currency
COPY currency_converter/*.py ./

# run
ENTRYPOINT ["python", "currency_converter.py"]