FROM python:3.6-alpine

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY requirements-api.txt requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add app
COPY currency_converter/api api
COPY currency_converter/currency currency

WORKDIR /usr/src/app/api

RUN chmod 774 entrypoint.sh

# run server
CMD ["./entrypoint.sh"]